const fs = require('fs');
const path = require('path');

let headers = [];
let code    = "";

let maxArgCount = 0;

function makeTypeSafe(name) {
    let out = "";
    for (const ch of name)
        if (ch == ',')
            out += " CM ";
        else
            out += ch;
    return out;
}

function codegenClass(cls) {
    for (const func of cls.functions) {
        const canHook = (typeof func.bindings.win == 'number') || (func.bindings.win == 'link');

        if (!canHook || func.kind != 'normal')
            continue;

        let skip = false;
        for (const arg of func.args)
            if (arg.type.trim() == 'gd::string' || arg.type.trim() == 'gd::string&') {
                skip = true;
            }

        if (skip)
            continue;

        const namespacedClassName = cls.name;

        const split = namespacedClassName.split('::');
        const className = split[split.length - 1];

        if (className == 'CCDisplayLinkDirector' && func.name == 'mainLoop')
            continue;

        if (func['return'] == 'cocos2d::ccColor3B')
            continue;

        if (className == 'PlayLayer' && (func.name == 'processCreateObjectsFromSetup' || func.name == 'setupHasCompleted'))
            continue;

        if (!headers.includes(className))
            headers.push(className);

        if (func['return'] != '' && func['return'] != 'void')
            code += "PROFILER_HOOK(" + makeTypeSafe(func['return']) + ", ";
        else
            code += "PROFILER_HOOK_VOID(";

        code += namespacedClassName + ", " + func.name + ", ";

        if (func.args.length > maxArgCount)
            maxArgCount = func.args.length;

        let num = 0;
        for (const arg of func.args) {
            if (num != 0)
                code += " CM ";
            
            code += makeTypeSafe(arg.type) + " p" + num;
            num++;
        }

        code += ", ";

        num = 0;
        for (const _ of func.args) {
            if (num != 0)
                code += " CM ";
            
            code += "p" + num;
            num++;
        }

        code += ")\n";
    }
}

function main() {
    const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'CodegenData.json')));

    for (const cls of data.classes)
        codegenClass(cls);

    let fullCode = "// This code has been generated by a script, specifically codegenProfilerHooks.js\n\n" +
                   "#include \"profiler.hpp\"\n\n";

    for (const header of headers)
        fullCode += `#include <Geode/modify/${header}.hpp>\n`;
    fullCode += "\n" + code;

    fs.writeFileSync(path.join(__dirname, 'profilerHooks.cpp'), fullCode);

    console.log("Maximum number or arguments a function has: " + maxArgCount);
}

main();